name: Prettier Verifier

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ node-version }}
        cache: 'npm'
        
    - name: Install packages
      run: yarn install
      
    - name: Run linter check
      run: yarn prettier -c .
